apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wp-db
  template:
    metadata:
      labels:
        app: wp-db
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "P@ssWord!!"
        - name: MYSQL_DATABASE
          value: wordpress
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: wp-db-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: wp-db-storage
        persistentVolumeClaim:
          claimName: wp-pvc