apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:latest
        ports:
        - containerPort: 80
        env:
        - name: WORDPRESS_DB_HOST
          value: wp-db-service
        - name: WORDPRESS_DB_USER
          value: root
        - name: WORDPRESS_DB_PASSWORD
          value: "P@ssWord!!" 
        - name: WORDPRESS_DB_NAME
          value: wordpress
        volumeMounts:
        - name: wp-content
          mountPath: /var/www/html
      volumes:
      - name: wp-content
        persistentVolumeClaim:
          claimName: wp-pvc

          